version: '3.8'

services:
  # Django приложение
  web:
    build: .
    container_name: django_app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn myproject.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DATABASE_URL=postgresql://${DJANGO_POSTGRES_USER}:${DJANGO_POSTGRES_PASSWORD}@db:5434/${DJANGO_POSTGRES_DB}
      - SECRET_KEY=your-production-secret-key-change-this
      - DJANGO_SETTINGS_MODULE=myproject.settings.production
    depends_on:
      - db
    restart: unless-stopped

  # PostgreSQL база данных
  db:
    image: postgres:16.4
    container_name: newsdb
    environment:
      - POSTGRES_DB=${DJANGO_POSTGRES_DB}
      - POSTGRES_USER=${DJANGO_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DJANGO_POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume: